config/routes.rb
Rails.application.routes.draw do
  get 'items/index'
  get 'welcome/index'

  resources :items

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    validates :name, presence: true
end

app/models/welcome.rb
class Welcome < ApplicationRecord
    validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
     before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    # byebug    
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path(@item), notice: "Hell yea!"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to items_path(@item), notice: "Done!"
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path(@item), notice: "GONE!"
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @welcome_message = "Welcome to the Item List App!"
  end
end
   

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/index.html.erb
<h1>Items</h1>
<% @items.each do |item| %>
  <p><%=item.name%></p>
<% end %>

app/views/items/new.html.erb
<h1>Add An Item!<h1>

<%=form_with(model: @item, url:items_path, method: :post) do |form| %>
    <%= form.label :name %>:
    <%= form.text_field :name %>
     <%= form.submit "Add" %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Message</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1><%= @welcome_message%></h1>

<%=link_to "Items", items_path%> <br/>
<%=link_to "Add New Item", new_item_path%>